import Navbar from "@components/layout/Navbar";
import "./globals.css";
import { ReduxProvider } from "providers/ReduxProvider";
import { PayPalProvider } from "providers/PayPalProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-neutral-950">
        <ReduxProvider>
          <PayPalProvider>
            <Navbar />
            {children}
          </PayPalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
